version: '3'

services:
  vector_db:
    image: pgvector/pgvector:pg14
    volumes:
      - vector_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd

volumes:
  vector_data: